import { describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';
import {
    inferExcelSheetType,
    parseClipboardMatrix,
    parseNumericMatrix,
    parseNumericVector,
    readExcelFile
} from './fileIO';

describe('strict numeric parsing', () => {
    it('preserves an empty pasted cell and reports its original coordinate', () => {
        const clipboard = parseClipboardMatrix('1\t\t3\n4\t5\t6');
        expect(clipboard.data[0]).toEqual(['1', '', '3']);

        const parsed = parseNumericMatrix(clipboard.data);
        expect(parsed.matrix[0]).toHaveLength(3);
        expect(Number.isNaN(parsed.matrix[0][1])).toBe(true);
        expect(parsed.errors).toEqual(expect.arrayContaining([
            expect.objectContaining({ row: 1, column: 2, message: '单元格为空' })
        ]));
    });

    it('rejects partial numbers instead of silently accepting parseFloat prefixes', () => {
        const parsed = parseNumericMatrix([['12abc']]);
        expect(parsed.errors[0].message).toBe('不是有限数值');
    });

    it('reads a row-labelled x sheet as a vector', () => {
        const parsed = parseNumericVector([
            ['sector', 'x'],
            ['A', '100'],
            ['B', '200']
        ], true);

        expect(parsed.errors).toEqual([]);
        expect(parsed.rowNames).toEqual(['A', 'B']);
        expect(parsed.vector).toEqual([100, 200]);
    });

    it('preserves every value in a header-labelled row vector without a row label', () => {
        const parsed = parseNumericVector([
            ['A', 'B'],
            ['100', '200']
        ], true);

        expect(parsed.errors).toEqual([]);
        expect(parsed.vector).toEqual([100, 200]);
    });

    it('rejects a two-dimensional x table', () => {
        const parsed = parseNumericVector([
            ['1', '2'],
            ['3', '4']
        ]);
        expect(parsed.vector).toEqual([]);
        expect(parsed.errors.map(error => error.message)).toContain('总产出 x 必须是一行或一列');
    });
});

describe('Excel workbook import', () => {
    it('reads a workbook generated by the maintained SheetJS package', async () => {
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(
            workbook,
            XLSX.utils.aoa_to_sheet([['sector', 'x'], ['A', 100], ['B', 200]]),
            'x'
        );
        const bytes = XLSX.write(workbook, { type: 'array', bookType: 'xlsx' });
        const file = new File([bytes], 'sample.xlsx');

        const result = await readExcelFile(file);

        expect(result.error).toBeUndefined();
        expect(result.sheets).toEqual([{ name: 'x', data: [
            ['sector', 'x'],
            ['A', '100'],
            ['B', '200']
        ] }]);
    });

    it('maps only explicit input sheet names and skips result sheets', () => {
        expect(inferExcelSheetType('Z_中间投入')).toBe('Z');
        expect(inferExcelSheetType('x_总产出')).toBe('x');
        expect(inferExcelSheetType('Y_最终需求')).toBe('Y');
        expect(inferExcelSheetType('VA_增加值')).toBe('VA');
        expect(inferExcelSheetType('F_卫星账户')).toBe('F');
        expect(inferExcelSheetType('L_Leontief逆')).toBe('');
        expect(inferExcelSheetType('VA_Coef_增加值系数')).toBe('');
        expect(inferExcelSheetType('产出乘数')).toBe('');
        expect(inferExcelSheetType('最终需求足迹')).toBe('');
    });
});
